### ISSUE TITLE
Navmesh algorithm

### ISSUE THREAD

**Issue by alwayswdc** [pikol93/NavigationMesh#1]
Is your algorithm for creating navmesh and pathfinding consistent with recast&detour, and is its performance faster than that of Recast & Detour？

**Comment by pikol93** [comment]
Considering this was a hobby project developed in a very short period of time, I am fairly certain that it is in no way comperable to Recast & Detour. I also did not develop this with said library in mind so I cannot say for sure that my algorithm is consistent with it in any form.
